'use client';

export default function Legal() {
  const V = {bg:'#060C18',s:'#0A1628',tx:'#EDE5D3',mu:'#8A9BAB',am:'#E88C12',br:'#1B2E48'};
  const FF = "'Georgia, serif'";

  return (
    <div style={{background:V.bg,color:V.tx,fontFamily:'Georgia, serif',minHeight:'100vh',padding:'60px 32px'}}>
      <div style={{maxWidth:720,margin:'0 auto'}}>

        <div style={{marginBottom:60}}>
          <p style={{fontSize:12,letterSpacing:6,color:V.am,marginBottom:12}}>BORN FROM</p>
          <h1 style={{fontSize:36,fontWeight:400,marginBottom:8}}>Terms of Service</h1>
          <p style={{fontSize:14,color:V.mu,marginBottom:40}}>Last updated: April 2026</p>

          {[
            {title:'1. Acceptance of Terms', body:'By accessing or using Born From ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.'},
            {title:'2. Description of Service', body:'Born From provides AI-generated elemental archetype profile reports based on birth date input. These reports are cultural and entertainment content based on the Korean Four Pillars (사주) calendrical classification system. All content is generated by artificial intelligence and is provided for entertainment and self-reflection purposes only.'},
            {title:'3. Not Professional Advice', body:'The content provided by Born From is for entertainment purposes only. It does not constitute medical, psychological, financial, legal, or any other form of professional advice. We make no predictive or factual claims about future events. Users should not make important life decisions based solely on content from Born From.'},
            {title:'4. Digital Products', body:'All purchases on Born From are for digital content delivered instantly via the web. By completing a purchase, you acknowledge that you are purchasing digital content and consent to immediate delivery.'},
            {title:'5. Intellectual Property', body:'All content, design, and code on Born From is the intellectual property of Born From. You may not reproduce, distribute, or create derivative works without written permission.'},
            {title:'6. Limitation of Liability', body:'Born From is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the specific product in question.'},
            {title:'7. Changes to Terms', body:'We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.'},
            {title:'8. Contact', body:'For questions about these terms, contact us at: bornfrom.co@gmail.com'},
          ].map((s,i) => (
            <div key={i} style={{marginBottom:28}}>
              <h2 style={{fontSize:18,fontWeight:400,color:V.am,marginBottom:8}}>{s.title}</h2>
              <p style={{fontSize:16,color:V.mu,lineHeight:1.8}}>{s.body}</p>
            </div>
          ))}
        </div>

        <div style={{borderTop:`1px solid ${V.br}`,paddingTop:60}}>
          <h1 style={{fontSize:36,fontWeight:400,marginBottom:8}}>Refund Policy</h1>
          <p style={{fontSize:14,color:V.mu,marginBottom:40}}>Last updated: April 2026</p>

          {[
            {title:'Our Policy', body:'All sales of digital content on Born From are final. Because our products are AI-generated digital reports delivered instantly upon purchase, we generally do not offer refunds once content has been accessed.'},
            {title:'Exceptions', body:'We will issue a full refund in the following cases: (1) You were charged but did not receive access to your content due to a technical error. (2) You were charged more than once for the same product. (3) The content delivered was completely blank or unreadable.'},
            {title:'How to Request a Refund', body:'To request a refund under the exceptions above, contact us within 7 days of purchase at bornfrom.co@gmail.com with your order details. We will respond within 2 business days.'},
            {title:'Processing', body:'Approved refunds will be processed through your original payment method within 5-10 business days.'},
          ].map((s,i) => (
            <div key={i} style={{marginBottom:28}}>
              <h2 style={{fontSize:18,fontWeight:400,color:V.am,marginBottom:8}}>{s.title}</h2>
              <p style={{fontSize:16,color:V.mu,lineHeight:1.8}}>{s.body}</p>
            </div>
          ))}

          <div style={{marginTop:40,padding:'20px',background:V.s,border:`1px solid ${V.br}`}}>
            <p style={{fontSize:14,color:V.mu,lineHeight:1.8}}>
              Contact: <span style={{color:V.tx}}>bornfrom.co@gmail.com</span><br/>
              Website: <span style={{color:V.tx}}>bornfrom.co</span>
            </p>
          </div>
        </div>

      </div>
    </div>
  );
}
